### PR TITLE
Enable external_predictions for short model in benchmarks

### PR DESCRIPTION
**Pull request by lucien1011**
### Description
This pull request adds an optional input arguments `fit_args` to the function `sensitivity_benchmark` in the class `DoubleML`. Most importantly, this addition will enable the usage of `external_predictions` when fitting short models for sensitivity analysis.

The new argument has to be in a nested dictionary like this:
````
dataset = dml.DoubleMLData(
    df,
    y_col='y',
    d_col='d',
    x_cols=cov_cols,
    force_all_x_finite=False,
)

dml_irm = dml.DoubleMLIRM(
    dataset,
    ml_g=RandomForestRegressor(), #dummy learner only
    ml_l=RandomForestClassifier(),
)

# Some user-specific codes to calculate external_predictions and put in the following columns
# df['d_prop'] df['y_pred_d0'] df['y_pred_d1']

bm = dml_irm.sensitivity_benchmark(
    benchmarking_set=['covariate_to_be_tested'],
    fit_args=dict(
        external_predictions=(
            d=dict(
                ml_m=df['d_prop'].to_numpy().reshape(-1,1),
                ml_g0=df['y_pred_d0'].to_numpy().reshape(-1,1),
                ml_g1=df['y_pred_d1'].to_numpy().reshape(-1,1),
            ),
        ),
    ),
)
````

### Reference to Issues or PRs
No related issues or PRs to my knowledge.

### PR Checklist
Please fill out this PR checklist (see our [contributing guidelines](https://github.com/DoubleML/doubleml-for-py/blob/main/CONTRIBUTING.md#checklist-for-pull-requests-pr) for details).

- [x] The title of the pull request summarizes the changes made.
- [x] The PR contains a detailed description of all changes and additions.
- [x] References to related issues or PRs are added.
- [x] The code passes all (unit) tests.
- [x] Enhancements or new feature are equipped with unit tests.
- [x] The changes adhere to the PEP8 standards.

### CODE REVIEW

**Comment by SvenKlaassen** [comment]
Thanks @lucien1011. I really like this addition.

Maybe you can change the default value to `None` (to avoid mutatable defaults).
And a small unit test would also be great.  Maybe add a small comparison to compare the external predictions to fitted learners (as in https://github.com/DoubleML/doubleml-for-py/blob/main/doubleml/plm/tests/test_plr_external_predictions.py) to https://github.com/DoubleML/doubleml-for-py/blob/main/doubleml/tests/test_sensitivity.py
Further, a unit test for exceptions of input arguments in https://github.com/DoubleML/doubleml-for-py/blob/main/doubleml/tests/test_exceptions_ext_preds.py would be nice.

**Comment by lucien1011** [comment]
@SvenKlaassen Thanks for the comments. I will implement those accordingly and update this PR.

**Comment by lucien1011** [comment]
@SvenKlaassen I have updated the PR with the following three items:

1. Change the default value of fit_args to be None
2. Added a unit test to test the type of fit_args (it must be a dictionary)
3. Added a unit test to test the values of delta_theta with and without external_predictions.

**Review by SvenKlaassen — APPROVED** [review]

**Comment by SvenKlaassen** [comment]
I will check the coverage on a different branch and then merge into `main`

**Pull request merged**
